version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0

      - run:
          name: login to docker
          command: |
            docker login --username "${DOCKER_ID_USER}" --password "${DOCKER_ID_PASSWORD}"

      - run:
          name: Pull image
          command: |
            docker pull "${DOCKER_ID_USER}/${APP_NAME}:latest"

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from "${DOCKER_ID_USER}/${APP_NAME}:latest" -t "${APP_NAME}" .

      - run:
          name: Run tests
          command: |
            docker-compose -f circle-ci-docker-compose.yml up -d postgis
            sleep 5
            docker-compose -f circle-ci-docker-compose.yml run --rm test_container rake db:create db:migrate
            docker-compose -f circle-ci-docker-compose.yml run --rm test_container rspec

      # comments
      - run:
          name: Push application Docker image
          command: |
            docker tag "${APP_NAME}" "${DOCKER_ID_USER}/${APP_NAME}:$(echo $CIRCLE_SHA1 | cut -c -7)"
            docker push "${DOCKER_ID_USER}/${APP_NAME}:$(echo $CIRCLE_SHA1 | cut -c -7)"

            docker tag "${APP_NAME}" "${DOCKER_ID_USER}/${APP_NAME}:${CIRCLE_BRANCH}"
            docker push "${DOCKER_ID_USER}/${APP_NAME}:${CIRCLE_BRANCH}"

            if [ $CIRCLE_BRANCH = 'master' ]; then
              docker tag "${APP_NAME}" "${DOCKER_ID_USER}/${APP_NAME}:latest"
              docker push "${DOCKER_ID_USER}/${APP_NAME}:latest"
            fi


