default: &default
  adapter: postgis
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  pool: 20
  timeout: 5000

stage:
  <<: *default
  pool: 10
  timeout: 20000

playground:
  <<: *default
  pool: 10
  timeout: 20000
